### ISSUE TITLE
An error occurs when the Destination is Snowflake.

### ISSUE THREAD

**Issue by cavernaria** [fivetran/dbt_zendesk_source#3]
I am using snowflake. I am using dbt packeage (zendesk).

I have a table here called "Group". The "Group" has to be enclosed in double-cotations. Because that's a Snowflake specification.
However, dbt automatically adds a single quote and I get an error.

This is the error.

```
Database Error in model stg_zendesk_group (models/stg_zendesk_group.sql)
001003 (42000): SQL compilation error:
syntax error line 5 at position 43 unexpected 'group'.
syntax error line 7 at position 0 unexpected ')'.
compiled SQL at target/run/zendesk_source/models/stg_zendesk_group.sql
```

Adding double quotes on the model side results in an error because when you "dbt run", dbt encloses it in a single coat.
I would like to know the specific code that can solve this problem.

**Comment by bbirand** [comment]
This is related to the issue: https://github.com/fivetran/dbt_zendesk/issues/3

**Comment by jeffthink** [comment]
@fivetran-kristin I don't mean to pile on (thanks for building open-source software!), but since the fix is already in master, I think the main step required is a new version release

It's hard to work around this issue at the moment (e.g. by pointing to github branch instead of release number) since the non-source zendesk repository (the one that most end users like me use) has its packages.yml depend on this one

Thanks!

**Comment by fivetran-kristin** [comment]
we're in the process of publishing our new releases. You'll be able to upgrade soon! Thanks for the patience :)

**Comment by jeffthink** [comment]
@fivetran-kristin thanks for the update!

**Comment by fivetran-kristin** [comment]
Please upgrade to the latest version, which fixes this issue.

```
packages:
  - package: fivetran/zendesk
    version: 0.1.1
```
